### ISSUE TITLE
Can't see others pings [Bukkit Server, Fabric Client]

### ISSUE THREAD

**Issue by QarthO** [RXJpaw/Minecraft-Ping-Wheel-Plugin#1]
Installed the "Ping Wheel-Plugin" on the server, and installed "Ping Wheel" mod on fabric client.

Log into server, can see and hear my own pings, but no one can see my pings, and I can't see theres.

Server Logs: https://mclo.gs/OeyBOVk

Client Logs: https://mclo.gs/PHnGTRX

I tried giving both players OP but they still can't see each others pings, so I don't think its permission related.

They are both in the Global Channel (default).

Is there a port that needs to be opened on the server, similarly like how the Simple Voice Chat mod/plugin need to work together?
What am I missing?

**Comment by RXJpaw** [comment]
Thank you for reporting this incident!

I fixed the mentioned bug with [Release 1.0.1](https://github.com/RXJpaw/Minecraft-Ping-Wheel-Plugin/releases/tag/v1.0.1-1.18%2B).

Can you confirm the plugin is working as intended now?

**Comment by QarthO** [comment]
Yes, its now working! Thanks for the quick fix
