### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by SpiritOTHawk** [RXJpaw/Minecraft-Ping-Wheel-Plugin#3]

**Comment by RXJpaw** [comment]
Hey, thank you for using the Ping Wheel-Plugin!

I've tested the plugin with @LukenSkyne and everything seems to be working as intended in every version between 1.18.2 and 1.21!

Can you please further describe your issue?

**Comment by SpiritOTHawk** [comment]
Hey, I'm sorry, I just realized I made a mistake on my own.
